version: '3.8'
services:
  myapi:
    build:
      context: .  # it has Dockerfile
      dockerfile: Dockerfile  # Dockerfile name
    container_name: myapi
    ports:
      - "5049:8080"  # ourbound port:inbound port (ports are in the container)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
